### ISSUE TITLE
Populating a model association 

### ISSUE THREAD

**Issue by nitinprajapati1404** [balderdashy/sails-docs#1080]
Hello 

I have a many to many relations between user and company.

So i would like to fetch all active companies with user details so i am keep the query in populate but it gives me follwing error

`{ UsageError: Invalid populate(s).
   Details:
     Could not populate `company` because of ambiguous usage.  This is a singular ("model") association, which means it never refers to more than _one_ associated record.  So passing in subcriteria (i.e. as the second argument to `.populate()`) is not supported for this association, since it generally wouldn't make any sense.  But that's the trouble-- it looks like some sort of a subcriteria (or something) _was_ provided!
   (Note that subcriterias consisting ONLY of `omit` or `select` are a special case that _does_ make sense.  This usage will be supported in a future version of Waterline.)
   
   Here's what was passed in:
   { where: { is_active: true } }
   
       at /var/www/html/aditapp/api/controllers/v1/numbers/NumbersController.js:58:38
       at /var/www/html/aditapp/node_modules/async/dist/async.js:3671:13
       at replenish (/var/www/html/aditapp/node_modules/async/dist/async.js:884:21)
       at iterateeCallback (/var/www/html/aditapp/node_modules/async/dist/async.js:869:21)
       at /var/www/html/aditapp/node_modules/async/dist/async.js:847:20
       at /var/www/html/aditapp/node_modules/async/dist/async.js:3676:17
       at /var/www/html/aditapp/node_modules/async/dist/async.js:339:31
       at /var/www/html/aditapp/api/controllers/v1/numbers/NumbersController.js:36:32
       at proceedToFinalAfterExecLC (/var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:1151:14)
       at proceedToInterceptsAndChecks (/var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:909:12)
       at proceedToAfterExecSpinlocks (/var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:841:10)
       at /var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:303:7
       at _afterTalkingToAdapter (/var/www/html/aditapp/node_modules/waterline/lib/waterline/methods/count.js:227:16)
       at Object.success (/var/www/html/aditapp/node_modules/sails-mongo/lib/private/do-with-connection.js:254:18)
       at /var/www/html/aditapp/node_modules/machine/lib/private/help-build-machine.js:1517:30
       at proceedToFinalAfterExecLC (/var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:1181:16)
       at proceedToInterceptsAndChecks (/var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:909:12)
       at proceedToAfterExecSpinlocks (/var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:841:10)
       at /var/www/html/aditapp/node_modules/parley/lib/private/Deferred.js:303:7
       at /var/www/html/aditapp/node_modules/machine/lib/private/help-build-machine.js:954:24
       at Function.handlerCbs.success (/var/www/html/aditapp/node_modules/machine/lib/private/help-build-machine.js:814:26)
       at Object.fn (/var/www/html/aditapp/node_modules/sails-mongo/lib/private/machines/release-connection.js:77:18)
     name: 'UsageError',
     code: 'E_INVALID_POPULATES',
     details:
      'Could not populate `company` because of ambiguous usage.  This is a singular ("model") association, which means it never refers to more than _one_ associated record.  So passing in subcriteria (i.e. as the second argument to `.populate()`) is not supported for this association, since it generally wouldn\'t make any sense.  But that\'s the trouble-- it looks like some sort of a subcriteria (or something) _was_ provided!\n(Note that subcriterias consisting ONLY of `omit` or `select` are a special case that _does_ make sense.  This usage will be supported in a future version of Waterline.)\n\nHere\'s what was passed in:\n{ where: { is_active: true } }' } }`

I use following code

`User.find({}).populate('company',{where:{is_active:true}});`

**Comment by raqem** [comment]
Hi @nitinprajapati1404, 
  Your trying to fetch a list of users that have a company associated with them that has `is_active` set to true, is that right? 
 Where do you want these results to go? Do you want to access it in the front end to make a list or table of the results?

**Comment by nitinprajapati1404** [comment]
@raqem yes.. exactly i want that,

**Comment by raqem** [comment]
Hmmm I would consider trying to use _.pluck on your page script to get the data on the front end from your db.  
 something like:

```
        let users = _.pluck(user, 'company');
        let usersWithCompany = _.pluck(company , 'isActive');
        this.usersWithActiveCompany = usersWithCompany;
```
and remember to add `usersWithActiveCompany: undefined` to your page data. 

this is just a thought I am not 100% this would work for you but maybe do more research on lodash pluck and other lodash functions.

**Comment by nitinprajapati1404** [comment]
Hi @raqem  

Thanks for suggestion,

This is like data manipulation by code . so this is the last priority which we can do.
Thanks

**Comment by raqem** [comment]
@nitinprajapati1404 Took a second look with Mike and I noticed something else that might make sense to look at:

If this is a many to many association, shouldn't it be `.populate('companies')` (plural?)

The error message you saw originally is because the second argument to `populate()` is not supported for "has one" aka "singular" associations (e.g. "company").  It's only supported for "has many" aka "plural" associations (e.g. "companies").  So I think the solution here is to change your model so that your association is `companies: { collection: 'Company', via: 'users' }` (assuming your association on the other side is called "users").
