### ISSUE TITLE
Error while connecting to MongoDB Atlas free tier cluster - 'no SNI name sent'

### ISSUE THREAD

**Issue by mwang55** [balderdashy/sails-docs#960]
When trying to connect to a MongoDB Atlas free tier cluster, I'm receiving the following error:

    error: A hook (`orm`) failed to load!
    error:
    error: Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
     Error details:
     { MongoError: no SNI name sent, make sure using a MongoDB 3.4+ driver/shell.
         at Function.MongoError.create (..\node_modules\sails-mongo\node_modules\mongodb-core\lib\error.js:31:11)
    at commandCallback (..\node_modules\sails-mongo\node_modules\mongodb-core\lib\topologies\server.js:1206:66)
    at Callbacks.emit (..\node_modules\sails-mongo\node_modules\mongodb-core\lib\topologies\server.js:119:3)
    at Connection.messageHandler (..\node_modules\sails-mongo\node_modules\mongodb-core\lib\topologies\server.js:371:23)
    at TLSSocket.<anonymous> (..\node_modules\sails-mongo\node_modules\mongodb-core\lib\connection\connection.js:301:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)
      name: 'MongoError',
      message: 'no SNI name sent, make sure using a MongoDB 3.4+ driver/shell.',
       ok: 0,
      errmsg: 'no SNI name sent, make sure using a MongoDB 3.4+ driver/shell.',
      code: 8000,
      codeName: 'AtlasError' }

The versions for sails, sails-mongo, mongodb are as follows:

`"sails": "^1.0.0-45",
"sails-mongo": "^0.12.2",
"mongodb": "^3.0.1"`

Configuration in sails.config.connections is the following:

      mongodbAtlasConn: {
      adapter: 'sails-mongo',
      url: 'mongodb://username:password@cluster-shard-00-01-hostname:27017,cluster-shard-00-02-hostname:27017,cluster-shard-00-03-hostname:27017/test?ssl=true&replicaSet=cluster-shard-0&authSource=admin',
      ssl: true
    }

My understanding is that the MongoDB Atlas free tier [requires](https://docs.atlas.mongodb.com/driver-connection/#prerequisites) SNI support from the client and Sails isn't sending it while trying to establish the SSL connection with Atlas. Is there a way to configure it in Sails to enable SNI support?

Thanks!

**Comment by rachaelshaw** [comment]
@mwang55 have you tried upgrading your version of sails-mongo? Looks like you need to be on a newer version for it to work with Atlas. (See https://stackoverflow.com/a/42726285)

**Comment by mwang55** [comment]
I see, apparently when I was running `npm install sails-mongo@latest` it was installing v0.12.2 but I was able to get v0.12.3 by running `npm install sails-mongo@0.12.3`.

Thanks for the response!
